// Generated by Duxner Maker — the one seam between the API and Postgres. Two implementations ship:
// db/pg.ts (node-postgres, the real server) and db/pglite.ts (PGlite: tests and Maker's in-browser test server).
export interface QueryOptions {
  /** Rows as arrays of values in column order (what Drizzle's proxy driver wants). */
  rowMode?: 'array';
}

export interface Db {
  /** One statement with $1, $2... parameters. */
  query<R = Record<string, unknown>>(sql: string, params?: unknown[], options?: QueryOptions): Promise<{ rows: R[] }>;
  /** A script of several statements, no parameters (migrations). */
  exec(sql: string): Promise<void>;
  /** Runs fn inside BEGIN/COMMIT (ROLLBACK when it throws). Nested calls join the outer transaction. */
  transaction<T>(fn: (tx: Db) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}
