// Generated by Duxner Maker — reads db/migrations/*.sql from disk (Node only).
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Migration } from './migrate.ts';

export async function readMigrationsDir(dir: string): Promise<Migration[]> {
  const names = (await readdir(dir)).filter((f) => f.endsWith('.sql')).sort();
  const out: Migration[] = [];
  for (const f of names) out.push({ name: f.slice(0, -4), sql: await readFile(join(dir, f), 'utf8') });
  return out;
}
