// Generated by Duxner Maker — runs db/migrations/*.sql in name order, each in its own transaction, and records
// them in the _migrations table (with a checksum, so an edited old migration is caught instead of silently skipped).
import type { Db } from './driver.ts';
import { sha256Hex } from '../lib/ids.ts';

export interface Migration {
  /** "0001_init" (the file name without .sql). */
  name: string;
  sql: string;
}

export interface MigrateOptions {
  /** Run migrations marked "-- duxner:destructive" that were not confirmed in Maker. */
  allowDestructive?: boolean;
  log?: (line: string) => void;
}

const NAME = /^[0-9]{4}_[a-z0-9_]+$/;
const UNCONFIRMED = /^-- duxner:destructive(?![ \t]+confirmed)/m;

const normalize = (sql: string) => sql.replace(/\r\n/g, '\n');

export async function ensureMigrationsTable(db: Db): Promise<void> {
  await db.exec('CREATE TABLE IF NOT EXISTS "_migrations" ("name" text PRIMARY KEY, "checksum" text NOT NULL, "applied_at" timestamptz NOT NULL DEFAULT now());');
}

/** The newest applied migration, or null (also when none ran yet). */
export async function latestMigration(db: Db): Promise<string | null> {
  const t = await db.query<{ t: string | null }>("SELECT to_regclass('_migrations')::text AS t");
  if (!t.rows[0] || !t.rows[0].t) return null;
  const r = await db.query<{ name: string | null }>('SELECT max("name") AS "name" FROM "_migrations"');
  return r.rows[0] ? r.rows[0].name : null;
}

export async function runMigrations(db: Db, migrations: Migration[], opts: MigrateOptions = {}): Promise<{ applied: string[]; latest: string | null }> {
  const log = opts.log ?? (() => {});
  const list = [...migrations].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const seen = new Set<string>();
  for (const m of list) {
    if (!NAME.test(m.name)) throw new Error('"' + m.name + '" is not a migration name. Use 0001_what_it_does.sql.');
    const n = m.name.slice(0, 4);
    if (seen.has(n)) throw new Error('Two migrations are numbered ' + n + '. Renumber one of them.');
    seen.add(n);
  }
  await ensureMigrationsTable(db);
  const applied: string[] = [];
  for (const m of list) {
    const sql = normalize(m.sql);
    const checksum = await sha256Hex(sql);
    const ran = await db.transaction(async (tx) => {
      // One runner at a time, even with several replicas starting together.
      await tx.query('SELECT pg_advisory_xact_lock(727274101)');
      const row = (await tx.query<{ checksum: string }>('SELECT "checksum" FROM "_migrations" WHERE "name" = $1::text', [m.name])).rows[0];
      if (row) {
        if (row.checksum !== checksum) throw new Error('Migration ' + m.name + ' was changed after it was applied. Add a new migration instead of editing an old one.');
        return false;
      }
      if (UNCONFIRMED.test(sql) && !opts.allowDestructive) {
        throw new Error('Migration ' + m.name + ' can delete data and was not confirmed. Review it, then run with ALLOW_DESTRUCTIVE_MIGRATIONS=true.');
      }
      await tx.exec(sql);
      await tx.query('INSERT INTO "_migrations" ("name", "checksum") VALUES ($1::text, $2::text)', [m.name, checksum]);
      return true;
    });
    if (ran) {
      applied.push(m.name);
      log('Applied migration ' + m.name);
    }
  }
  return { applied, latest: await latestMigration(db) };
}
