// Generated by Duxner Maker — Drizzle ORM over the Db seam (drizzle's proxy driver), so typed queries work the
// same on node-postgres and on PGlite. Use it in src/custom.ts: ctx.orm.select().from(tasksTable)...
import { drizzle } from 'drizzle-orm/pg-proxy';
import * as schema from '../../db/schema.ts';
import type { Db } from './driver.ts';

export function createOrm(db: Db) {
  return drizzle(
    async (sql, params, method) => {
      const r = await db.query(sql, params, method === 'all' ? { rowMode: 'array' } : undefined);
      return { rows: r.rows };
    },
    { schema },
  );
}

export type Orm = ReturnType<typeof createOrm>;
