// Generated by Duxner Maker — node-postgres behind the Db seam.
import pg from 'pg';
import type { Db } from './driver.ts';

interface Client {
  query(config: { text: string; values?: unknown[]; rowMode?: 'array' }): Promise<{ rows: unknown[] }>;
  query(text: string): Promise<unknown>;
}

function over(client: Client, transaction: Db['transaction'], close: () => Promise<void>): Db {
  return {
    async query<R>(sql: string, params?: unknown[], options?: { rowMode?: 'array' }) {
      const r = await client.query({ text: sql, values: params ?? [], rowMode: options?.rowMode });
      return { rows: r.rows as R[] };
    },
    async exec(sql: string) {
      await client.query(sql);
    },
    transaction,
    close,
  };
}

export function createPgDb(connectionString: string, options: { max?: number } = {}): Db {
  const pool = new pg.Pool({ connectionString, max: options.max ?? 10 });
  const transaction = async <T>(fn: (tx: Db) => Promise<T>): Promise<T> => {
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      const tx: Db = over(client as unknown as Client, (inner) => inner(tx), async () => {});
      const result = await fn(tx);
      await client.query('COMMIT');
      return result;
    } catch (e) {
      await client.query('ROLLBACK').catch(() => {});
      throw e;
    } finally {
      client.release();
    }
  };
  return over(pool as unknown as Client, transaction, () => pool.end());
}
