// Generated by Duxner Maker — PGlite (Postgres in WebAssembly) behind the Db seam: the tests and Maker's
// in-browser test server use it. Typed structurally, so the server does not depend on @electric-sql/pglite.
import type { Db } from './driver.ts';

export interface PgliteQueryable {
  query(sql: string, params?: unknown[], options?: { rowMode?: 'array' | 'object' }): Promise<{ rows: unknown[] }>;
  exec(sql: string): Promise<unknown>;
}

export interface PgliteLike extends PgliteQueryable {
  transaction<T>(fn: (tx: PgliteQueryable) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}

function over(q: PgliteQueryable, transaction: Db['transaction'], close: () => Promise<void>): Db {
  return {
    async query<R>(sql: string, params?: unknown[], options?: { rowMode?: 'array' }) {
      const r = await q.query(sql, params ?? [], options?.rowMode ? { rowMode: options.rowMode } : undefined);
      return { rows: r.rows as R[] };
    },
    async exec(sql: string) {
      await q.exec(sql);
    },
    transaction,
    close,
  };
}

export function fromPglite(pg: PgliteLike): Db {
  const transaction = <T>(fn: (tx: Db) => Promise<T>): Promise<T> =>
    pg.transaction((raw) => {
      const tx: Db = over(raw, (inner) => inner(tx), async () => {});
      return fn(tx);
    });
  return over(pg, transaction, () => pg.close());
}
