// Generated by Duxner Maker — the one error shape every route answers with.
export type ErrorCode =
  | 'invalid'
  | 'unauthenticated'
  | 'denied'
  | 'not-found'
  | 'conflict'
  | 'too-big'
  | 'rate-limited'
  | 'internal'
  | 'unavailable';

export const ERROR_STATUS: Record<ErrorCode, number> = {
  invalid: 400,
  unauthenticated: 401,
  denied: 403,
  'not-found': 404,
  conflict: 409,
  'too-big': 413,
  'rate-limited': 429,
  internal: 500,
  unavailable: 503,
};

export class ApiError extends Error {
  readonly code: ErrorCode;
  readonly status: number;
  constructor(code: ErrorCode, message: string) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
    this.status = ERROR_STATUS[code];
  }
}

/** { "error": { "code": "invalid", "message": "..." } } */
export function errorBody(e: ApiError): { error: { code: ErrorCode; message: string } } {
  return { error: { code: e.code, message: e.message } };
}

/** A Postgres error (node-postgres and PGlite both expose .code) as an ApiError, or null. */
export function fromDbError(e: unknown): ApiError | null {
  const code = typeof e === 'object' && e !== null ? (e as { code?: unknown }).code : undefined;
  if (code === '23503') return new ApiError('invalid', 'This points to a record that does not exist.');
  if (code === '23505') return new ApiError('conflict', 'That is already taken.');
  if (code === '22P02' || code === '22007' || code === '22008' || code === '22003') return new ApiError('invalid', 'A value has the wrong form for its field.');
  return null;
}
