// Generated by Duxner Maker — ids, clocks and hashing on Web Crypto (Node, browsers and Workers alike).
const ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyz';

function randomChars(n: number): string {
  const bytes = new Uint8Array(n);
  crypto.getRandomValues(bytes);
  let out = '';
  for (const b of bytes) out += ALPHABET[b % 36];
  return out;
}

/** Time-ordered, collision-resistant record id: 9 chars of time + 12 random (the same form platform.db uses on the device). */
export function newRecordId(now: number = Date.now()): string {
  return now.toString(36).padStart(9, '0') + randomChars(12);
}

/** A clock that never repeats or goes back inside this process, so createdAt order is insertion order. */
export function monotonicClock(now: () => number = Date.now): () => string {
  let last = 0;
  return () => {
    const t = Math.max(now(), last + 1);
    last = t;
    return new Date(t).toISOString();
  };
}

export function base64url(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

export function fromBase64url(text: string): Uint8Array {
  const s = atob(text.replace(/-/g, '+').replace(/_/g, '/'));
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

/** An unguessable token (refresh tokens, magic links). Only its hash is stored. */
export function randomToken(bytes = 32): string {
  const b = new Uint8Array(bytes);
  crypto.getRandomValues(b);
  return base64url(b);
}

export async function sha256Hex(text: string): Promise<string> {
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)));
  let out = '';
  for (const b of digest) out += b.toString(16).padStart(2, '0');
  return out;
}

/** Compares without leaking where the first difference is. */
export function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}
