// Generated by Duxner Maker — a simple in-memory token bucket per client. One process only: behind several
// replicas each keeps its own count (put a shared limiter, e.g. in your proxy, in front if that matters).
import type { Context, MiddlewareHandler } from 'hono';
import { ApiError, errorBody } from './errors.ts';

export interface RateLimiter {
  take(key: string): { ok: boolean; retryAfter: number };
}

export interface RateLimitOptions {
  /** Steady rate. 0 turns the limiter off. */
  perMinute: number;
  /** Bucket size (default: perMinute) — how many requests may come at once. */
  burst?: number;
  now?: () => number;
  /** Clients remembered at most; the oldest is forgotten first. */
  maxKeys?: number;
}

export function createRateLimiter(opts: RateLimitOptions): RateLimiter {
  if (opts.perMinute <= 0) return { take: () => ({ ok: true, retryAfter: 0 }) };
  const capacity = opts.burst ?? opts.perMinute;
  const perMs = opts.perMinute / 60000;
  const now = opts.now ?? Date.now;
  const maxKeys = opts.maxKeys ?? 10000;
  const buckets = new Map<string, { tokens: number; at: number }>();
  return {
    take(key) {
      const t = now();
      let b = buckets.get(key);
      if (!b) {
        if (buckets.size >= maxKeys) {
          const oldest = buckets.keys().next().value;
          if (oldest !== undefined) buckets.delete(oldest);
        }
        b = { tokens: capacity, at: t };
        buckets.set(key, b);
      } else {
        b.tokens = Math.min(capacity, b.tokens + (t - b.at) * perMs);
        b.at = t;
      }
      if (b.tokens >= 1) {
        b.tokens -= 1;
        return { ok: true, retryAfter: 0 };
      }
      return { ok: false, retryAfter: Math.max(1, Math.ceil((1 - b.tokens) / perMs / 1000)) };
    },
  };
}

export function rateLimit(limiter: RateLimiter, keyOf: (c: Context) => string, scope: string): MiddlewareHandler {
  return async (c, next) => {
    const r = limiter.take(scope + ':' + keyOf(c));
    if (!r.ok) {
      c.header('Retry-After', String(r.retryAfter));
      return c.json(errorBody(new ApiError('rate-limited', 'Too many requests. Try again in ' + r.retryAfter + ' s.')), 429);
    }
    await next();
  };
}
