-- Generated by Duxner Maker from data/schema.json. Applied in order by scripts/migrate.ts (table _migrations).

-- Sign-in: people, refresh tokens (stored hashed, rotated on use) and magic links (hashed, one use).
CREATE TABLE "auth_users" (
  "id" text PRIMARY KEY,
  "email" text NOT NULL UNIQUE,
  "password_hash" text,
  "email_verified_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE "auth_refresh_tokens" (
  "id" text PRIMARY KEY,
  "user_id" text NOT NULL REFERENCES "auth_users" ("id") ON DELETE CASCADE,
  "family" text NOT NULL,
  "token_hash" text NOT NULL UNIQUE,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "auth_refresh_tokens_user_id_idx" ON "auth_refresh_tokens" ("user_id");
CREATE INDEX "auth_refresh_tokens_family_idx" ON "auth_refresh_tokens" ("family");
CREATE TABLE "auth_magic_links" (
  "token_hash" text PRIMARY KEY,
  "email" text NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "used_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- notes: User's quick text notes
CREATE TABLE "notes" (
  "id" text PRIMARY KEY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "title" text,
  "content" text,
  "tags" jsonb
);

-- tags: Tags for organizing notes
CREATE TABLE "tags" (
  "id" text PRIMARY KEY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "name" text
);

-- searchHistory: Recent search terms
CREATE TABLE "searchHistory" (
  "id" text PRIMARY KEY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "query" text
);
