// Generated by Duxner Maker — change events inside this process (what GET /v1/:collection/events streams).
// With several replicas, each only sees its own writes; relay them through Postgres LISTEN/NOTIFY if you scale out.
export interface Change {
  collection: string;
  type: 'add' | 'put' | 'update' | 'remove';
  id: string;
  /** Set for per-person collections: only that person hears about it. */
  ownerId: string | null;
}

export interface ChangeBus {
  emit(change: Change): void;
  subscribe(collection: string, listener: (change: Change) => void): () => void;
}

export function createChangeBus(): ChangeBus {
  const listeners = new Map<string, Set<(change: Change) => void>>();
  return {
    emit(change) {
      for (const l of [...(listeners.get(change.collection) ?? [])]) {
        try {
          l(change);
        } catch (e) {
          console.error(e);
        }
      }
    },
    subscribe(collection, listener) {
      let set = listeners.get(collection);
      if (!set) listeners.set(collection, (set = new Set()));
      set.add(listener);
      return () => {
        listeners.get(collection)?.delete(listener);
      };
    },
  };
}
