// Generated by Duxner Maker — the REST contract, the same verbs as platform.db:
//   GET    /v1/:collection            ?where.<field>.<op>=<json>&orderBy=f.asc&limit=&offset=  → { records: [...] }
//   GET    /v1/:collection/count      ?where...                                                 → { count: n }
//   GET    /v1/:collection/events     server-sent events "change" {type,id}  (token: Authorization or ?access_token=)
//   GET    /v1/:collection/:id        → the record, or 404
//   POST   /v1/:collection            body: fields → 201 the record
//   PUT    /v1/:collection/:id        body: fields → 200 (replaced) or 201 (created) the record
//   PATCH  /v1/:collection/:id        body: some fields (null clears) → 200 the record, or 404
//   DELETE /v1/:collection/:id        → 204 (also when it was not there)
import { Hono } from 'hono';
import type { Context } from 'hono';
import { streamSSE } from 'hono/streaming';
import type { AppEnv } from '../app-env.ts';
import type { Config } from '../config.ts';
import { ApiError } from '../lib/errors.ts';
import { RestQueryError, decodeRestQuery, type RestQuery } from '../lib/rest-query.ts';
import type { Change, ChangeBus } from './events.ts';
import type { DataStore, Scope } from './store.ts';
import { MAX_RECORD_BYTES, collectionOf, type Model } from './validate.ts';

export interface DataRoutesDeps {
  store: DataStore;
  model: Model;
  bus: ChangeBus;
  config: Config;
  /** Seconds between keep-alive comments on an idle event stream. */
  heartbeatSeconds?: number;
}

function queryOf(c: Context): RestQuery {
  const params = new URL(c.req.url).searchParams;
  params.delete('access_token');
  try {
    return decodeRestQuery(params);
  } catch (e) {
    if (e instanceof RestQueryError) throw new ApiError('invalid', e.message);
    throw e;
  }
}

async function bodyOf(c: Context): Promise<unknown> {
  const declared = Number(c.req.header('content-length') ?? '0');
  if (declared > MAX_RECORD_BYTES * 2) throw new ApiError('too-big', 'The request is too big.');
  const text = await c.req.text();
  if (text.length > MAX_RECORD_BYTES * 2) throw new ApiError('too-big', 'The request is too big.');
  try {
    return JSON.parse(text);
  } catch {
    throw new ApiError('invalid', 'The request body must be JSON.');
  }
}

export function dataRoutes(deps: DataRoutesDeps): Hono<AppEnv> {
  const { store, model, bus, config } = deps;
  const routes = new Hono<AppEnv>();

  /**
   * Per-person collections need a signed-in person; shared ones too, unless SHARED_ACCESS=public-read and this is a
   * read, or SHARED_ACCESS=anyone (an app with no sign-in).
   */
  const scope = (c: Context<AppEnv>, write: boolean): Scope => {
    const col = collectionOf(model, c.req.param('collection') ?? '');
    const userId = c.get('userId');
    const open = col.owner !== 'user' && (config.sharedAccess === 'anyone' || (config.sharedAccess === 'public-read' && !write));
    if (!userId && !open) throw new ApiError('unauthenticated', 'Sign in first.');
    return { userId: userId ?? null };
  };
  const name = (c: Context<AppEnv>) => c.req.param('collection') ?? '';
  const idOf = (c: Context<AppEnv>) => c.req.param('id') ?? '';

  routes.get('/:collection/count', async (c) => {
    const s = scope(c, false);
    const q = queryOf(c);
    if (q.orderBy !== undefined || q.limit !== undefined || q.offset !== undefined) throw new ApiError('invalid', 'count takes only where.<field>.<op> filters.');
    return c.json({ count: await store.count(name(c), q.where, s) });
  });

  routes.get('/:collection/events', (c) => {
    const s = scope(c, false);
    const collection = name(c);
    const heartbeat = (deps.heartbeatSeconds ?? 25) * 1000;
    return streamSSE(c, async (stream) => {
      const queue: Change[] = [];
      let wake: (() => void) | null = null;
      let open = true;
      const off = bus.subscribe(collection, (ch) => {
        if (ch.ownerId !== null && ch.ownerId !== s.userId) return;
        queue.push(ch);
        if (wake) wake();
      });
      stream.onAbort(() => {
        open = false;
        off();
        if (wake) wake();
      });
      await stream.writeSSE({ event: 'ready', data: '{}' });
      while (open) {
        if (queue.length === 0) {
          const idle = await new Promise<boolean>((resolve) => {
            const timer = setTimeout(() => {
              wake = null;
              resolve(true);
            }, heartbeat);
            wake = () => {
              clearTimeout(timer);
              wake = null;
              resolve(false);
            };
          });
          if (idle && open) await stream.write(': keep-alive\n\n');
        }
        while (open && queue.length) {
          const ch = queue.shift() as Change;
          await stream.writeSSE({ event: 'change', data: JSON.stringify({ type: ch.type, id: ch.id }) });
        }
      }
      off();
    });
  });

  routes.get('/:collection/:id', async (c) => {
    const rec = await store.get(name(c), idOf(c), scope(c, false));
    if (!rec) throw new ApiError('not-found', 'There is no record "' + idOf(c) + '" in ' + name(c) + '.');
    return c.json(rec);
  });

  routes.get('/:collection', async (c) => {
    const s = scope(c, false);
    return c.json({ records: await store.list(name(c), queryOf(c), s) });
  });

  routes.post('/:collection', async (c) => {
    const s = scope(c, true);
    return c.json(await store.add(name(c), await bodyOf(c), s), 201);
  });

  routes.put('/:collection/:id', async (c) => {
    const s = scope(c, true);
    const r = await store.put(name(c), idOf(c), await bodyOf(c), s);
    return c.json(r.record, r.created ? 201 : 200);
  });

  routes.patch('/:collection/:id', async (c) => {
    const s = scope(c, true);
    return c.json(await store.update(name(c), idOf(c), await bodyOf(c), s));
  });

  routes.delete('/:collection/:id', async (c) => {
    await store.remove(name(c), idOf(c), scope(c, true));
    return c.body(null, 204);
  });

  return routes;
}
