// Generated by Duxner Maker — turns a checked query into parameterised SQL. Every value travels as a $n
// parameter of type text and is cast in SQL, so node-postgres and PGlite send exactly the same thing.
// Text compares with COLLATE "C" (byte order), which is how platform.db sorts on the device.
import type { Collection, Cond, FieldType, Order } from './validate.ts';

const SQL_TYPE: Record<FieldType, string> = {
  string: 'text',
  number: 'double precision',
  boolean: 'boolean',
  date: 'timestamptz',
  json: 'jsonb',
  ref: 'text',
};

export const ident = (name: string): string => '"' + name.replace(/"/g, '""') + '"';
export const columnOf = (field: string): string => (field === 'createdAt' ? 'created_at' : field === 'updatedAt' ? 'updated_at' : field);
const isText = (t: FieldType) => t === 'string' || t === 'ref';

/** Collects parameters; add() returns the placeholder with its cast. */
export function params() {
  const values: (string | null)[] = [];
  const add = (value: unknown, type: FieldType): string => {
    let text: string | null;
    if (value === null || value === undefined) text = null;
    else if (type === 'json') text = JSON.stringify(value);
    else if (type === 'boolean') text = value ? 'true' : 'false';
    else text = String(value);
    values.push(text);
    return '$' + values.length + '::text' + (isText(type) ? '' : '::' + SQL_TYPE[type]);
  };
  return { values, add };
}

type Add = (value: unknown, type: FieldType) => string;

function condSql(c: Cond, add: Add): string {
  const col = ident(columnOf(c.field));
  const sortable = isText(c.type) ? col + ' COLLATE "C"' : col;
  switch (c.op) {
    case 'eq':
      return c.value === null ? col + ' IS NULL' : col + ' = ' + add(c.value, c.type);
    case 'neq':
      return c.value === null ? col + ' IS NOT NULL' : col + ' IS DISTINCT FROM ' + add(c.value, c.type);
    case 'lt':
      return sortable + ' < ' + add(c.value, c.type);
    case 'lte':
      return sortable + ' <= ' + add(c.value, c.type);
    case 'gt':
      return sortable + ' > ' + add(c.value, c.type);
    case 'gte':
      return sortable + ' >= ' + add(c.value, c.type);
    case 'contains':
      return 'strpos(lower(' + col + '), lower(' + add(c.value, 'string') + ')) > 0';
    case 'in': {
      const list = c.value as unknown[];
      const parts: string[] = [];
      const present = list.filter((v) => v !== null);
      if (present.length) parts.push(col + ' IN (' + present.map((v) => add(v, c.type)).join(', ') + ')');
      if (present.length !== list.length) parts.push(col + ' IS NULL');
      return parts.length ? '(' + parts.join(' OR ') + ')' : 'FALSE';
    }
    default:
      throw new Error('unknown operator ' + c.op);
  }
}

/** " WHERE ..." (or ""), owner first when the collection is per-person. */
export function whereSql(conds: Cond[], ownerId: string | null, add: Add): string {
  const parts: string[] = [];
  if (ownerId !== null) parts.push('"owner_id" = ' + add(ownerId, 'string'));
  for (const c of conds) parts.push(condSql(c, add));
  return parts.length ? ' WHERE ' + parts.join(' AND ') : '';
}

/** Nulls last ascending, first descending; ties always break on id ascending (as on the device). */
export function orderSql(order: Order[]): string {
  const parts = order.map((o) => {
    const col = ident(columnOf(o.field)) + (isText(o.type) ? ' COLLATE "C"' : '');
    return col + (o.dir === 'asc' ? ' ASC NULLS LAST' : ' DESC NULLS FIRST');
  });
  parts.push('"id" COLLATE "C" ASC');
  return ' ORDER BY ' + parts.join(', ');
}

export function fieldColumns(c: Collection): [string, FieldType][] {
  return Object.entries(c.fields).map(([name, f]) => [name, f.type]);
}
