// Generated by Duxner Maker — the records API over Postgres: the same verbs and results as platform.db.
import type { Db } from '../db/driver.ts';
import { ApiError, fromDbError } from '../lib/errors.ts';
import { monotonicClock, newRecordId } from '../lib/ids.ts';
import type { RestQuery, RestWhere } from '../lib/rest-query.ts';
import type { ChangeBus } from './events.ts';
import { fieldColumns, ident, orderSql, params, whereSql } from './sql.ts';
import { RESERVED_IDS, checkId, checkSize, collectionOf, normalizeQuery, normalizeWhere, prepareData, type Collection, type Model } from './validate.ts';

export type DataRecord = { id: string; createdAt: string; updatedAt: string } & Record<string, unknown>;

/** Who is asking: records of per-person collections are only ever those of userId. */
export interface Scope {
  userId: string | null;
}

export interface DataStore {
  get(collection: string, id: string, scope: Scope): Promise<DataRecord | null>;
  list(collection: string, query: RestQuery, scope: Scope): Promise<DataRecord[]>;
  count(collection: string, where: RestWhere | undefined, scope: Scope): Promise<number>;
  add(collection: string, data: unknown, scope: Scope): Promise<DataRecord>;
  /** Creates or wholly replaces; created tells which. */
  put(collection: string, id: string, data: unknown, scope: Scope): Promise<{ record: DataRecord; created: boolean }>;
  update(collection: string, id: string, patch: unknown, scope: Scope): Promise<DataRecord>;
  /** True when something was deleted. */
  remove(collection: string, id: string, scope: Scope): Promise<boolean>;
}

export interface StoreOptions {
  now?: () => number;
  newId?: () => string;
}

const iso = (v: unknown): string => (v instanceof Date ? v.toISOString() : new Date(String(v)).toISOString());

/** A row as a record: platform fields, then the app's fields; empty (NULL) fields are left out. */
export function rowToRecord(c: Collection, row: Record<string, unknown>): DataRecord {
  const out: DataRecord = { id: String(row.id), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) };
  for (const [name, f] of Object.entries(c.fields)) {
    const v = row[name];
    if (v === null || v === undefined) continue;
    out[name] = f.type === 'date' ? iso(v) : v;
  }
  return out;
}

async function guard<T>(fn: () => Promise<T>): Promise<T> {
  try {
    return await fn();
  } catch (e) {
    throw fromDbError(e) ?? e;
  }
}

export function createDataStore(db: Db, model: Model, bus: ChangeBus, opts: StoreOptions = {}): DataStore {
  const stamp = monotonicClock(opts.now ?? Date.now);
  const newId = opts.newId ?? (() => newRecordId());

  const ownerOf = (c: Collection, scope: Scope): string | null => {
    if (c.owner !== 'user') return null;
    if (!scope.userId) throw new ApiError('unauthenticated', 'Sign in first.');
    return scope.userId;
  };

  const writeRow = (
    run: Db,
    name: string,
    c: Collection,
    id: string,
    owner: string | null,
    t: string,
    data: Record<string, unknown>,
    replace: boolean,
  ) => {
    const p = params();
    const cols = ['"id"'];
    const vals = [p.add(id, 'string')];
    if (owner !== null) {
      cols.push('"owner_id"');
      vals.push(p.add(owner, 'string'));
    }
    cols.push('"created_at"', '"updated_at"');
    vals.push(p.add(t, 'date'), p.add(t, 'date'));
    for (const [field, type] of fieldColumns(c)) {
      cols.push(ident(field));
      vals.push(p.add(data[field] === undefined ? null : data[field], type));
    }
    let sql = 'INSERT INTO ' + ident(name) + ' (' + cols.join(', ') + ') VALUES (' + vals.join(', ') + ')';
    if (replace) {
      const sets = ['"updated_at" = EXCLUDED."updated_at"', ...fieldColumns(c).map(([f]) => ident(f) + ' = EXCLUDED.' + ident(f))];
      sql += ' ON CONFLICT ("id") DO UPDATE SET ' + sets.join(', ');
      if (owner !== null) sql += ' WHERE ' + ident(name) + '."owner_id" = EXCLUDED."owner_id"';
      sql += ' RETURNING *, (xmax = 0) AS "__inserted"';
    } else sql += ' RETURNING *';
    return guard(() => run.query<Record<string, unknown>>(sql, p.values));
  };

  return {
    async get(name, id, scope) {
      const c = collectionOf(model, name);
      checkId(id, name);
      const p = params();
      const owner = ownerOf(c, scope);
      const sql = 'SELECT * FROM ' + ident(name) + whereSql([{ field: 'id', type: 'string', op: 'eq', value: id }], owner, p.add);
      const r = await guard(() => db.query<Record<string, unknown>>(sql, p.values));
      return r.rows[0] ? rowToRecord(c, r.rows[0]) : null;
    },

    async list(name, query, scope) {
      const c = collectionOf(model, name);
      const nq = normalizeQuery(model, name, query);
      const p = params();
      const owner = ownerOf(c, scope);
      let sql = 'SELECT * FROM ' + ident(name) + whereSql(nq.where, owner, p.add) + orderSql(nq.order);
      sql += ' LIMIT ' + p.add(nq.limit, 'number') + ' OFFSET ' + p.add(nq.offset, 'number');
      const r = await guard(() => db.query<Record<string, unknown>>(sql, p.values));
      return r.rows.map((row) => rowToRecord(c, row));
    },

    async count(name, where, scope) {
      const c = collectionOf(model, name);
      const conds = normalizeWhere(model, name, where);
      const p = params();
      const sql = 'SELECT count(*)::int AS "n" FROM ' + ident(name) + whereSql(conds, ownerOf(c, scope), p.add);
      const r = await guard(() => db.query<{ n: number }>(sql, p.values));
      return Number(r.rows[0] ? r.rows[0].n : 0);
    },

    async add(name, data, scope) {
      const c = collectionOf(model, name);
      const owner = ownerOf(c, scope);
      const clean = prepareData(model, name, data, 'create');
      const id = newId();
      const t = stamp();
      checkSize({ ...clean, id, createdAt: t, updatedAt: t }, name);
      const r = await writeRow(db, name, c, id, owner, t, clean, false);
      bus.emit({ collection: name, type: 'add', id, ownerId: owner });
      return rowToRecord(c, r.rows[0]);
    },

    async put(name, id, data, scope) {
      const c = collectionOf(model, name);
      checkId(id, name);
      if (RESERVED_IDS.includes(id)) throw new ApiError('invalid', '"' + id + '" can\'t be a record id: it is a word the API uses.');
      const owner = ownerOf(c, scope);
      const clean = prepareData(model, name, data, 'create');
      const t = stamp();
      checkSize({ ...clean, id, createdAt: t, updatedAt: t }, name);
      const r = await writeRow(db, name, c, id, owner, t, clean, true);
      const row = r.rows[0];
      if (!row) throw new ApiError('conflict', 'The id "' + id + '" is already used by a record you can\'t change.');
      const created = row.__inserted === true;
      bus.emit({ collection: name, type: created ? 'add' : 'put', id, ownerId: owner });
      return { record: rowToRecord(c, row), created };
    },

    async update(name, id, patch, scope) {
      const c = collectionOf(model, name);
      checkId(id, name);
      const owner = ownerOf(c, scope);
      const clean = prepareData(model, name, patch, 'patch');
      const record = await db.transaction(async (tx) => {
        const p = params();
        const sets = ['"updated_at" = ' + p.add(stamp(), 'date')];
        for (const [field, type] of fieldColumns(c)) if (clean[field] !== undefined) sets.push(ident(field) + ' = ' + p.add(clean[field], type));
        const sql = 'UPDATE ' + ident(name) + ' SET ' + sets.join(', ') + whereSql([{ field: 'id', type: 'string', op: 'eq', value: id }], owner, p.add) + ' RETURNING *';
        const r = await guard(() => tx.query<Record<string, unknown>>(sql, p.values));
        if (!r.rows[0]) throw new ApiError('not-found', 'There is no record "' + id + '" in ' + name + '.');
        const rec = rowToRecord(c, r.rows[0]);
        checkSize(rec, name);
        return rec;
      });
      bus.emit({ collection: name, type: 'update', id, ownerId: owner });
      return record;
    },

    async remove(name, id, scope) {
      const c = collectionOf(model, name);
      checkId(id, name);
      const owner = ownerOf(c, scope);
      const p = params();
      const sql = 'DELETE FROM ' + ident(name) + whereSql([{ field: 'id', type: 'string', op: 'eq', value: id }], owner, p.add) + ' RETURNING "id"';
      const r = await guard(() => db.query(sql, p.values));
      if (r.rows.length === 0) return false;
      bus.emit({ collection: name, type: 'remove', id, ownerId: owner });
      return true;
    },
  };
}
