// Generated by Duxner Maker — checks every request against the data model (db/model.ts), with the same rules
// and words as platform.db on the device.
import { ApiError } from '../lib/errors.ts';
import type { RestQuery } from '../lib/rest-query.ts';

export type FieldType = 'string' | 'number' | 'boolean' | 'date' | 'json' | 'ref';

export interface Field {
  type: FieldType;
  required?: boolean;
  default?: unknown;
  ref?: string;
  description?: string;
}

export interface Collection {
  fields: Record<string, Field>;
  indexes?: (string | string[])[];
  owner?: 'user' | 'shared';
  description?: string;
}

export interface Model {
  version: 1;
  collections: Record<string, Collection>;
}

export const MAX_LIMIT = 1000;
export const MAX_RECORD_BYTES = 1024 * 1024;
export const MAX_IN = 100;
export const SYSTEM_FIELDS: readonly string[] = ['id', 'createdAt', 'updatedAt'];
/** GET /v1/:collection/count and /events — so these can't be record ids. */
export const RESERVED_IDS: readonly string[] = ['count', 'events'];

const NAME = /^[A-Za-z][A-Za-z0-9_]{0,63}$/;
const ID = /^[A-Za-z0-9_-]{1,128}$/;
const FORBIDDEN = new Set(['__proto__', 'constructor', 'prototype']);
const OPS = ['eq', 'neq', 'lt', 'lte', 'gt', 'gte', 'in', 'contains'];
const own = (o: object, k: string) => Object.prototype.hasOwnProperty.call(o, k);
const invalid = (message: string) => new ApiError('invalid', message);
const isPlain = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v) && (Object.getPrototypeOf(v) === Object.prototype || Object.getPrototypeOf(v) === null);

const NEEDS: Record<FieldType, string> = {
  string: 'text',
  number: 'a number',
  boolean: 'true or false',
  date: 'a date (like 2026-10-07)',
  json: 'any JSON value',
  ref: 'the id of a record',
};

export function collectionOf(model: Model, name: string): Collection {
  if (!NAME.test(name) || !own(model.collections, name)) {
    throw new ApiError('not-found', 'There is no collection called "' + name.slice(0, 64) + '". The collections are: ' + Object.keys(model.collections).join(', ') + '.');
  }
  return model.collections[name];
}

export function checkId(id: string, collection: string): string {
  if (!ID.test(id)) throw invalid('"' + id.slice(0, 40) + '" can\'t be a record id in ' + collection + '. Use letters, numbers, _ and - (at most 128).');
  return id;
}

/** The value as stored, or undefined when it does not fit the type. */
export function coerce(type: FieldType, v: unknown): unknown {
  switch (type) {
    case 'string':
      return typeof v === 'string' ? v : undefined;
    case 'number':
      return typeof v === 'number' && Number.isFinite(v) ? v : undefined;
    case 'boolean':
      return typeof v === 'boolean' ? v : undefined;
    case 'date': {
      if (typeof v !== 'string' && typeof v !== 'number') return undefined;
      const t = typeof v === 'number' ? v : Date.parse(v);
      return Number.isFinite(t) ? new Date(t).toISOString() : undefined;
    }
    case 'ref':
      return typeof v === 'string' && ID.test(v) ? v : undefined;
    case 'json':
      return v;
  }
}

function checkJson(value: unknown, where: string, depth = 0): void {
  if (depth > 32) throw invalid(where + ' is nested too deeply.');
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return;
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw invalid(where + ' must be a real number.');
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((v, i) => checkJson(v, where + '[' + i + ']', depth + 1));
    return;
  }
  if (isPlain(value)) {
    for (const [k, v] of Object.entries(value)) {
      if (FORBIDDEN.has(k)) throw invalid(where + ' has a key called "' + k + '", which is not allowed.');
      checkJson(v, where + '.' + k, depth + 1);
    }
    return;
  }
  throw invalid(where + ' can\'t be saved: only text, numbers, true/false, lists and objects can.');
}

/**
 * The app's fields of a write, checked against the model: unknown fields and wrong types are refused,
 * id/createdAt/updatedAt are ignored, and on "create" defaults are filled in and required fields demanded.
 */
export function prepareData(model: Model, collection: string, data: unknown, mode: 'create' | 'patch'): Record<string, unknown> {
  const c = collectionOf(model, collection);
  if (!isPlain(data)) throw invalid('A record in ' + collection + ' must be an object of fields.');
  const out: Record<string, unknown> = {};
  for (const [k, raw] of Object.entries(data)) {
    if (SYSTEM_FIELDS.includes(k) || raw === undefined) continue;
    const f = own(c.fields, k) ? c.fields[k] : undefined;
    if (!f) throw invalid(collection + ' has no field called "' + k.slice(0, 64) + '". Its fields are: ' + (Object.keys(c.fields).join(', ') || '(none)') + '.');
    checkJson(raw, '"' + k + '" in ' + collection);
    if (raw === null) {
      if (f.required) throw invalid('"' + k + '" is required in ' + collection + ', so it can\'t be cleared.');
      out[k] = null;
      continue;
    }
    const stored = coerce(f.type, raw);
    if (stored === undefined) throw invalid('"' + k + '" in ' + collection + ' must be ' + (f.type === 'ref' && f.ref ? 'the id of a record in ' + f.ref : NEEDS[f.type]) + '.');
    out[k] = stored;
  }
  if (mode === 'create') {
    for (const [k, f] of Object.entries(c.fields)) {
      if (out[k] !== undefined && out[k] !== null) continue;
      if (f.default !== undefined && f.default !== null && out[k] === undefined) out[k] = coerce(f.type, JSON.parse(JSON.stringify(f.default)));
      else if (f.required) throw invalid('"' + k + '" is required in ' + collection + '.');
    }
  }
  return out;
}

export function checkSize(record: Record<string, unknown>, collection: string): void {
  const bytes = new TextEncoder().encode(JSON.stringify(record)).byteLength;
  if (bytes > MAX_RECORD_BYTES) {
    throw new ApiError('too-big', 'This record in ' + collection + ' is too big (' + Math.ceil(bytes / 1024) + ' KB; the limit is ' + MAX_RECORD_BYTES / 1024 + ' KB). Save large content as a file instead.');
  }
}

// ─── queries ───────────────────────────────────────────────

export interface Cond {
  field: string;
  type: FieldType;
  op: string;
  value: unknown;
}

export interface Order {
  field: string;
  type: FieldType;
  dir: 'asc' | 'desc';
}

export interface NormalQuery {
  where: Cond[];
  order: Order[];
  limit: number;
  offset: number;
}

function typeOf(c: Collection, collection: string, field: string, doing: string): FieldType {
  if (field === 'id') return 'string';
  if (field === 'createdAt' || field === 'updatedAt') return 'date';
  if (!NAME.test(field) || !own(c.fields, field)) throw invalid(collection + ' can\'t be ' + doing + ' by "' + field.slice(0, 64) + '": it has no field called that.');
  const t = c.fields[field].type;
  if (t === 'json') throw invalid(collection + ' can\'t be ' + doing + ' by "' + field + '": it holds JSON.');
  return t;
}

function scalarFor(type: FieldType, field: string, collection: string, op: string, v: unknown, allowNull: boolean): unknown {
  if (v === null) {
    if (allowNull) return null;
    throw invalid('"' + op + '" on "' + field + '" in ' + collection + ' needs a value, not null.');
  }
  if (type === 'boolean' && op !== 'eq' && op !== 'neq' && op !== 'in') throw invalid('"' + op + '" can\'t be used on "' + field + '" (true or false) in ' + collection + '.');
  const stored = type === 'ref' ? (typeof v === 'string' ? v : undefined) : coerce(type, v);
  if (stored === undefined) throw invalid('"' + op + '" on "' + field + '" in ' + collection + ' needs ' + NEEDS[type] + '.');
  return stored;
}

export function normalizeWhere(model: Model, collection: string, where: unknown): Cond[] {
  const c = collectionOf(model, collection);
  if (where === undefined || where === null) return [];
  if (!isPlain(where)) throw invalid('The filter for ' + collection + ' must be an object like { done: false }.');
  const out: Cond[] = [];
  for (const [field, raw] of Object.entries(where)) {
    const type = typeOf(c, collection, field, 'filtered');
    const cond = isPlain(raw) ? raw : { eq: raw };
    const entries = Object.entries(cond).filter(([, v]) => v !== undefined);
    if (entries.length === 0) throw invalid('The filter on "' + field + '" in ' + collection + ' is empty.');
    for (const [op, value] of entries) {
      if (!OPS.includes(op)) throw invalid('The filter on "' + field + '" in ' + collection + ' uses "' + op + '", which isn\'t supported. Use ' + OPS.join(', ') + '.');
      if (op === 'in') {
        if (!Array.isArray(value) || value.length > MAX_IN) throw invalid('"in" on "' + field + '" in ' + collection + ' needs a list of up to ' + MAX_IN + ' plain values.');
        out.push({ field, type, op, value: value.map((v) => scalarFor(type, field, collection, op, v, true)) });
      } else if (op === 'contains') {
        if (type !== 'string' && type !== 'ref') throw invalid('"contains" works on text fields; "' + field + '" in ' + collection + ' is not text.');
        if (typeof value !== 'string') throw invalid('"contains" on "' + field + '" in ' + collection + ' needs text.');
        out.push({ field, type, op, value });
      } else {
        out.push({ field, type, op, value: scalarFor(type, field, collection, op, value, op === 'eq' || op === 'neq') });
      }
    }
  }
  return out;
}

export function normalizeQuery(model: Model, collection: string, q: RestQuery): NormalQuery {
  const c = collectionOf(model, collection);
  const where = normalizeWhere(model, collection, q.where);
  const raw = q.orderBy === undefined ? [] : Array.isArray(q.orderBy) ? q.orderBy : [q.orderBy];
  if (raw.length > 4) throw invalid(collection + ' can be sorted by at most 4 fields.');
  const order: Order[] = raw.map((o) => ({ field: o.field, type: typeOf(c, collection, o.field, 'sorted'), dir: o.dir === 'desc' ? 'desc' : 'asc' }));
  if (order.length === 0) order.push({ field: 'createdAt', type: 'date', dir: 'asc' });
  const limit = q.limit ?? MAX_LIMIT;
  const offset = q.offset ?? 0;
  if (!Number.isInteger(limit) || limit < 0 || limit > MAX_LIMIT) throw invalid('The limit for ' + collection + ' must be a whole number from 0 to ' + MAX_LIMIT + '.');
  if (!Number.isInteger(offset) || offset < 0 || offset > 10000000) throw invalid('The offset for ' + collection + ' must be a whole number of 0 or more.');
  return { where, order, limit, offset };
}
