// Generated by Duxner Maker — how sign-in emails leave the server. Pluggable: pass any Mailer to createApp.
// Default "console" prints the message (fine on your own machine; the link in it signs someone in, so don't
// use it where others can read the logs). "webhook" POSTs the message as JSON to your mail service or relay.
import type { Env } from '../config.ts';

export interface MailMessage {
  to: string;
  subject: string;
  text: string;
}

export interface Mailer {
  send(message: MailMessage): Promise<void>;
}

export function consoleMailer(log: (line: string) => void = console.log): Mailer {
  return {
    async send(m) {
      log('[mail] to ' + m.to + ' — ' + m.subject + '\n' + m.text);
    },
  };
}

export function webhookMailer(url: string, token?: string): Mailer {
  return {
    async send(m) {
      const headers: Record<string, string> = { 'content-type': 'application/json' };
      if (token) headers.authorization = 'Bearer ' + token;
      const r = await fetch(url, { method: 'POST', headers, body: JSON.stringify(m) });
      if (!r.ok) throw new Error('The mail webhook answered ' + r.status + '.');
    },
  };
}

/** MAILER=console (default) | webhook (MAILER_WEBHOOK_URL, optional MAILER_WEBHOOK_TOKEN). */
export function mailerFromEnv(env: Env): Mailer {
  const kind = (env.MAILER ?? 'console').trim();
  if (kind === 'webhook') {
    const url = (env.MAILER_WEBHOOK_URL ?? '').trim();
    if (!/^https?:\/\//.test(url)) throw new Error('MAILER=webhook needs MAILER_WEBHOOK_URL (https://...).');
    return webhookMailer(url, env.MAILER_WEBHOOK_TOKEN || undefined);
  }
  if (kind !== 'console') throw new Error('MAILER must be console or webhook.');
  return consoleMailer();
}
