// Generated by Duxner Maker — reads "Authorization: Bearer <access token>" (or ?access_token= on event
// streams, which browsers open without headers) and sets c.var.userId. A bad token is a 401, never "anonymous".
import type { Context, MiddlewareHandler } from 'hono';
import type { AppEnv } from '../app-env.ts';
import type { Config } from '../config.ts';
import { ApiError } from '../lib/errors.ts';
import { verifyAccessToken } from './tokens.ts';

export function authenticate(config: Config): MiddlewareHandler<AppEnv> {
  return async (c, next) => {
    let token: string | null = null;
    const header = c.req.header('authorization');
    if (header) {
      const m = /^Bearer[ ]+([A-Za-z0-9._~+\/=-]+)$/i.exec(header.trim());
      if (!m) throw new ApiError('unauthenticated', 'The Authorization header must be "Bearer <access token>".');
      token = m[1];
    } else if (c.req.method === 'GET' && c.req.path.endsWith('/events')) {
      token = c.req.query('access_token') ?? null;
    }
    let userId: string | null = null;
    if (token) {
      userId = await verifyAccessToken(config, token);
      if (!userId) throw new ApiError('unauthenticated', 'Your sign-in has expired. Sign in again.');
    }
    c.set('userId', userId);
    await next();
  };
}

/** The signed-in person's id, or a 401. */
export function requireUser(c: Context<AppEnv>): string {
  const id = c.get('userId');
  if (!id) throw new ApiError('unauthenticated', 'Sign in first.');
  return id;
}
