// Generated by Duxner Maker — password hashing on Web Crypto (PBKDF2-HMAC-SHA256), no native dependency.
import { ApiError } from '../lib/errors.ts';
import { base64url, fromBase64url, timingSafeEqual } from '../lib/ids.ts';

const PREFIX = 'pbkdf2-sha256';

async function derive(password: string, salt: Uint8Array, rounds: number): Promise<Uint8Array> {
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', hash: 'SHA-256', salt: salt as Uint8Array<ArrayBuffer>, iterations: rounds }, key, 256);
  return new Uint8Array(bits);
}

export function checkNewPassword(password: unknown): string {
  if (typeof password !== 'string' || password.length < 8) throw new ApiError('invalid', 'The password needs at least 8 characters.');
  if (password.length > 256) throw new ApiError('invalid', 'The password can have at most 256 characters.');
  return password;
}

export async function hashPassword(password: string, rounds: number): Promise<string> {
  const salt = new Uint8Array(16);
  crypto.getRandomValues(salt);
  return [PREFIX, String(rounds), base64url(salt), base64url(await derive(password, salt, rounds))].join('$');
}

export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [prefix, rounds, salt, hash] = stored.split('$');
  const n = Number(rounds);
  if (prefix !== PREFIX || !Number.isInteger(n) || n < 1 || !salt || !hash) return false;
  return timingSafeEqual(await derive(password, fromBase64url(salt), n), fromBase64url(hash));
}

/** True when the stored hash used fewer rounds than configured now (re-hash after a good sign-in). */
export function needsRehash(stored: string, rounds: number): boolean {
  const n = Number(stored.split('$')[1]);
  return !Number.isInteger(n) || n < rounds;
}
