// Generated by Duxner Maker — /v1/auth/*:
//   POST signup {email,password} → 201 {user, accessToken, refreshToken, tokenType, expiresIn}
//   POST login {email,password} → 200 same          POST refresh {refreshToken} → 200 new tokens (old one stops working)
//   POST logout {refreshToken} → 204               GET me → {id, email, emailVerified}
//   POST magic-link {email} → 202 (always; sends a link when sign-in by link is possible)
//   POST magic-link/verify {token} → 200 {user, ...tokens} (creates the account when SIGNUP=open)
import { Hono } from 'hono';
import type { Context } from 'hono';
import type { AppEnv } from '../app-env.ts';
import type { Config } from '../config.ts';
import type { Db } from '../db/driver.ts';
import { ApiError } from '../lib/errors.ts';
import { newRecordId, randomToken, sha256Hex } from '../lib/ids.ts';
import type { Mailer } from './mailer.ts';
import { requireUser } from './middleware.ts';
import { checkNewPassword, hashPassword, needsRehash, verifyPassword } from './password.ts';
import { issueTokens, revokeRefreshToken, rotateRefreshToken } from './tokens.ts';

export interface AuthRoutesDeps {
  db: Db;
  config: Config;
  mailer: Mailer;
}

const EMAIL = /^[^\s@]{1,64}@[^\s@]{1,253}\.[^\s@]{1,63}$/;

function emailOf(v: unknown): string {
  const e = typeof v === 'string' ? v.trim().toLowerCase() : '';
  if (!EMAIL.test(e)) throw new ApiError('invalid', 'Enter a valid email address.');
  return e;
}

async function body(c: Context): Promise<Record<string, unknown>> {
  try {
    const v = await c.req.json();
    if (typeof v === 'object' && v !== null && !Array.isArray(v)) return v as Record<string, unknown>;
  } catch {
    // fall through
  }
  throw new ApiError('invalid', 'The request body must be a JSON object.');
}

export function authRoutes(deps: AuthRoutesDeps): Hono<AppEnv> {
  const { db, config, mailer } = deps;
  const routes = new Hono<AppEnv>();
  let dummy: Promise<string> | null = null;
  const wrong = () => new ApiError('unauthenticated', 'Wrong email or password.');

  routes.post('/signup', async (c) => {
    if (config.signup !== 'open') throw new ApiError('denied', 'New accounts are closed on this server.');
    const b = await body(c);
    const email = emailOf(b.email);
    const hash = await hashPassword(checkNewPassword(b.password), config.passwordIterations);
    const r = await db.query<{ id: string }>(
      'INSERT INTO "auth_users" ("id", "email", "password_hash") VALUES ($1::text, $2::text, $3::text) ON CONFLICT ("email") DO NOTHING RETURNING "id"',
      [newRecordId(), email, hash],
    );
    if (!r.rows[0]) throw new ApiError('conflict', 'There is already an account with this email. Sign in instead.');
    return c.json({ user: { id: r.rows[0].id, email }, ...(await issueTokens(db, config, r.rows[0].id)) }, 201);
  });

  routes.post('/login', async (c) => {
    const b = await body(c);
    const email = emailOf(b.email);
    const password = typeof b.password === 'string' ? b.password : '';
    const user = (await db.query<{ id: string; password_hash: string | null }>('SELECT "id", "password_hash" FROM "auth_users" WHERE "email" = $1::text', [email])).rows[0];
    if (!user || !user.password_hash) {
      // Same work as a real check, so the answer time doesn't tell whether the account exists.
      await verifyPassword(password, await (dummy ??= hashPassword('not-a-password', config.passwordIterations)));
      throw wrong();
    }
    if (!(await verifyPassword(password, user.password_hash))) throw wrong();
    if (needsRehash(user.password_hash, config.passwordIterations)) {
      await db.query('UPDATE "auth_users" SET "password_hash" = $1::text WHERE "id" = $2::text', [await hashPassword(password, config.passwordIterations), user.id]);
    }
    return c.json({ user: { id: user.id, email }, ...(await issueTokens(db, config, user.id)) });
  });

  routes.post('/refresh', async (c) => {
    const b = await body(c);
    return c.json(await rotateRefreshToken(db, config, b.refreshToken));
  });

  routes.post('/logout', async (c) => {
    const b = await body(c);
    await revokeRefreshToken(db, b.refreshToken);
    return c.body(null, 204);
  });

  routes.get('/me', async (c) => {
    const id = requireUser(c);
    const u = (await db.query<{ email: string; email_verified_at: unknown }>('SELECT "email", "email_verified_at" FROM "auth_users" WHERE "id" = $1::text', [id])).rows[0];
    if (!u) throw new ApiError('unauthenticated', 'This account no longer exists.');
    return c.json({ id, email: u.email, emailVerified: u.email_verified_at !== null });
  });

  routes.post('/magic-link', async (c) => {
    if (!config.magicLinkUrl) throw new ApiError('unavailable', 'Sign-in links are off on this server (MAGIC_LINK_URL is not set).');
    const b = await body(c);
    const email = emailOf(b.email);
    const exists = (await db.query('SELECT 1 FROM "auth_users" WHERE "email" = $1::text', [email])).rows.length > 0;
    if (exists || config.signup === 'open') {
      const token = randomToken(32);
      await db.query('INSERT INTO "auth_magic_links" ("token_hash", "email", "expires_at") VALUES ($1::text, $2::text, $3::text::timestamptz)', [
        await sha256Hex(token),
        email,
        new Date(Date.now() + config.magicLinkTtl * 1000).toISOString(),
      ]);
      const link = config.magicLinkUrl + (config.magicLinkUrl.includes('?') ? '&' : '?') + 'token=' + encodeURIComponent(token);
      await mailer.send({
        to: email,
        subject: 'Your sign-in link',
        text: 'Open this link to sign in (it works once, for ' + Math.round(config.magicLinkTtl / 60) + ' minutes):\n' + link + '\n\nIf you did not ask for it, ignore this email.',
      });
    }
    // The same answer either way, so this can't be used to find out who has an account.
    return c.json({ ok: true }, 202);
  });

  routes.post('/magic-link/verify', async (c) => {
    const b = await body(c);
    if (typeof b.token !== 'string' || b.token.length < 20 || b.token.length > 200) throw new ApiError('unauthenticated', 'This sign-in link is not valid.');
    const hash = await sha256Hex(b.token);
    const user = await db.transaction(async (tx) => {
      const link = (
        await tx.query<{ email: string }>(
          'UPDATE "auth_magic_links" SET "used_at" = now() WHERE "token_hash" = $1::text AND "used_at" IS NULL AND "expires_at" > now() RETURNING "email"',
          [hash],
        )
      ).rows[0];
      if (!link) return null;
      const found = (await tx.query<{ id: string }>('UPDATE "auth_users" SET "email_verified_at" = coalesce("email_verified_at", now()) WHERE "email" = $1::text RETURNING "id"', [link.email])).rows[0];
      if (found) return { id: found.id, email: link.email };
      if (config.signup !== 'open') return null;
      const id = newRecordId();
      await tx.query('INSERT INTO "auth_users" ("id", "email", "email_verified_at") VALUES ($1::text, $2::text, now())', [id, link.email]);
      return { id, email: link.email };
    });
    if (!user) throw new ApiError('unauthenticated', 'This sign-in link has expired or was already used.');
    return c.json({ user, ...(await issueTokens(db, config, user.id)) });
  });

  return routes;
}
