// Generated by Duxner Maker — short-lived access tokens (JWT HS256) and rotating refresh tokens.
import { sign, verify } from 'hono/jwt';
import type { Config } from '../config.ts';
import type { Db } from '../db/driver.ts';
import { ApiError } from '../lib/errors.ts';
import { newRecordId, randomToken, sha256Hex } from '../lib/ids.ts';

export interface Tokens {
  accessToken: string;
  refreshToken: string;
  tokenType: 'Bearer';
  /** Seconds until the access token expires. */
  expiresIn: number;
}

export async function signAccessToken(config: Config, userId: string): Promise<string> {
  const iat = Math.floor(Date.now() / 1000);
  return sign({ sub: userId, typ: 'access', iat, exp: iat + config.accessTokenTtl }, config.jwtSecret, 'HS256');
}

/** The user id, or null when the token is not a valid, unexpired access token of this server. */
export async function verifyAccessToken(config: Config, token: string): Promise<string | null> {
  try {
    const p = await verify(token, config.jwtSecret, 'HS256');
    return p.typ === 'access' && typeof p.sub === 'string' ? p.sub : null;
  } catch {
    return null;
  }
}

/** A new access token + refresh token. family groups the refresh tokens of one sign-in. */
export async function issueTokens(db: Db, config: Config, userId: string, family?: string): Promise<Tokens> {
  const refreshToken = randomToken(32);
  await db.query(
    'INSERT INTO "auth_refresh_tokens" ("id", "user_id", "family", "token_hash", "expires_at") VALUES ($1::text, $2::text, $3::text, $4::text, $5::text::timestamptz)',
    [newRecordId(), userId, family ?? newRecordId(), await sha256Hex(refreshToken), new Date(Date.now() + config.refreshTokenTtl * 1000).toISOString()],
  );
  return { accessToken: await signAccessToken(config, userId), refreshToken, tokenType: 'Bearer', expiresIn: config.accessTokenTtl };
}

const expired = () => new ApiError('unauthenticated', 'Your sign-in has expired. Sign in again.');

/** Swaps a refresh token for new tokens. Using an already-swapped one ends that whole sign-in (it was copied). */
export async function rotateRefreshToken(db: Db, config: Config, refreshToken: unknown): Promise<Tokens> {
  if (typeof refreshToken !== 'string' || refreshToken.length < 20 || refreshToken.length > 200) throw expired();
  const hash = await sha256Hex(refreshToken);
  const result = await db.transaction(async (tx) => {
    const row = (
      await tx.query<{ id: string; user_id: string; family: string; expires_at: Date | string; revoked_at: unknown }>(
        'SELECT "id", "user_id", "family", "expires_at", "revoked_at" FROM "auth_refresh_tokens" WHERE "token_hash" = $1::text FOR UPDATE',
        [hash],
      )
    ).rows[0];
    if (!row) return null;
    if (row.revoked_at !== null) {
      await tx.query('UPDATE "auth_refresh_tokens" SET "revoked_at" = now() WHERE "family" = $1::text AND "revoked_at" IS NULL', [row.family]);
      return null;
    }
    if (new Date(row.expires_at).getTime() <= Date.now()) return null;
    await tx.query('UPDATE "auth_refresh_tokens" SET "revoked_at" = now() WHERE "id" = $1::text', [row.id]);
    return issueTokens(tx, config, row.user_id, row.family);
  });
  if (!result) throw expired();
  return result;
}

/** Signs out the sign-in this refresh token belongs to. Unknown tokens are ignored. */
export async function revokeRefreshToken(db: Db, refreshToken: unknown): Promise<void> {
  if (typeof refreshToken !== 'string' || refreshToken.length > 200) return;
  await db.query(
    'UPDATE "auth_refresh_tokens" SET "revoked_at" = now() WHERE "revoked_at" IS NULL AND "family" = (SELECT "family" FROM "auth_refresh_tokens" WHERE "token_hash" = $1::text)',
    [await sha256Hex(refreshToken)],
  );
}
