// Generated by Duxner Maker — the whole API as one Hono app, independent of where it runs: src/index.ts
// serves it on Node with node-postgres; Maker runs the same app in a browser Worker over PGlite.
import { Hono } from 'hono';
import type { Context } from 'hono';
import { cors } from 'hono/cors';
import type { AppEnv } from './app-env.ts';
import { authenticate, requireUser } from './auth/middleware.ts';
import { consoleMailer, type Mailer } from './auth/mailer.ts';
import { authRoutes } from './auth/routes.ts';
import type { Config } from './config.ts';
import { registerCustomRoutes } from './custom.ts';
import { createChangeBus, type ChangeBus } from './data/events.ts';
import { dataRoutes } from './data/routes.ts';
import { createDataStore, type DataStore } from './data/store.ts';
import type { Model } from './data/validate.ts';
import type { Db } from './db/driver.ts';
import { latestMigration } from './db/migrate.ts';
import { createOrm, type Orm } from './db/orm.ts';
import { ApiError, errorBody, fromDbError } from './lib/errors.ts';
import { createRateLimiter, rateLimit } from './lib/rate-limit.ts';
import { MODEL } from '../db/model.ts';

export interface AppDeps {
  db: Db;
  config: Config;
  /** Default: the generated db/model.ts. */
  model?: Model;
  /** Default: print messages to the console. */
  mailer?: Mailer;
  /** The caller's address for rate limiting (src/index.ts reads it from the socket). */
  clientIp?: (c: Context) => string;
  /** Clock for record timestamps and rate limits (tests). */
  now?: () => number;
  log?: (line: string) => void;
}

/** What src/custom.ts gets for its own endpoints. */
export interface CustomContext {
  db: Db;
  orm: Orm;
  store: DataStore;
  bus: ChangeBus;
  config: Config;
  requireUser: (c: Context<AppEnv>) => string;
}

export function createApp(deps: AppDeps): Hono<AppEnv> {
  const { db, config } = deps;
  const model = deps.model ?? MODEL;
  const log = deps.log ?? ((line: string) => console.error(line));
  const bus = createChangeBus();
  const store = createDataStore(db, model, bus, { now: deps.now });
  const ipOf = (c: Context): string => {
    if (config.trustProxy) {
      const fwd = c.req.header('x-forwarded-for');
      if (fwd) return fwd.split(',')[0].trim();
    }
    return deps.clientIp ? deps.clientIp(c) : 'local';
  };

  const app = new Hono<AppEnv>();
  app.onError((err, c) => {
    const known = err instanceof ApiError ? err : fromDbError(err);
    if (known) return c.json(errorBody(known), known.status as 400);
    log('Unexpected error on ' + c.req.method + ' ' + c.req.path + ': ' + (err instanceof Error ? err.stack || err.message : String(err)));
    return c.json(errorBody(new ApiError('internal', 'Something went wrong on the server.')), 500);
  });
  app.notFound((c) => c.json(errorBody(new ApiError('not-found', 'There is nothing at ' + c.req.path + '.')), 404));

  if (config.allowedOrigins.length) {
    app.use(
      '*',
      cors({
        origin: config.allowedOrigins,
        allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        allowHeaders: ['Authorization', 'Content-Type'],
        maxAge: 600,
      }),
    );
  }

  app.get('/health', async (c) => {
    try {
      return c.json({ ok: true, version: config.version, migration: await latestMigration(db) });
    } catch {
      return c.json({ ok: false, version: config.version, migration: null }, 503);
    }
  });

  const now = deps.now;
  app.use('/v1/auth/*', rateLimit(createRateLimiter({ perMinute: config.authRateLimitPerMinute, now }), ipOf, 'auth'));
  app.use('/v1/*', rateLimit(createRateLimiter({ perMinute: config.rateLimitPerMinute, now }), ipOf, 'api'));
  app.use('/v1/*', authenticate(config));
  app.route('/v1/auth', authRoutes({ db, config, mailer: deps.mailer ?? consoleMailer() }));
  // Your own endpoints first, so they win over /v1/:collection.
  registerCustomRoutes(app, { db, orm: createOrm(db), store, bus, config, requireUser });
  app.route('/v1', dataRoutes({ store, model, bus, config }));
  return app;
}
