// Generated by Duxner Maker — every setting comes from the environment (see .env.example). No secret lives in code.
import { VERSION } from './version.ts';

export interface Config {
  /** HS256 key for access tokens. Required; at least 32 characters. */
  jwtSecret: string;
  /** Seconds an access token lasts (default 900 = 15 minutes). */
  accessTokenTtl: number;
  /** Seconds a refresh token lasts (default 2592000 = 30 days). Each use replaces it. */
  refreshTokenTtl: number;
  /** Seconds a magic link lasts (default 900). */
  magicLinkTtl: number;
  /** The app page a magic link opens; the token is added as ?token=... Unset = magic links are off. */
  magicLinkUrl: string | null;
  /** Origins allowed to call the API from a browser (CORS). Empty = none. */
  allowedOrigins: string[];
  /** Requests per minute per client to /v1 (0 = no limit). */
  rateLimitPerMinute: number;
  /** Requests per minute per client to /v1/auth (sign-up, sign-in, links). */
  authRateLimitPerMinute: number;
  /** Read the client address from X-Forwarded-For (only behind your own proxy). */
  trustProxy: boolean;
  /** PBKDF2-SHA256 rounds for new password hashes. */
  passwordIterations: number;
  /** "open": anyone can create an account; "closed": only existing accounts sign in. */
  signup: 'open' | 'closed';
  /**
   * Who can use shared collections: "signed-in" (default), "public-read" (anyone may read; writing still needs sign-in)
   * or "anyone" (an app with no sign-in: anyone who can reach the server reads and writes them; per-person
   * collections still need sign-in).
   */
  sharedAccess: 'signed-in' | 'public-read' | 'anyone';
  version: string;
  port: number;
}

export type Env = Record<string, string | undefined>;

export class ConfigError extends Error {
  readonly problems: string[];
  constructor(problems: string[]) {
    super('The server is not configured:\n- ' + problems.join('\n- '));
    this.name = 'ConfigError';
    this.problems = problems;
  }
}

export function readConfig(env: Env): Config {
  const problems: string[] = [];
  const int = (name: string, fallback: number, min: number, max: number): number => {
    const raw = env[name];
    if (raw === undefined || raw.trim() === '') return fallback;
    const n = Number(raw);
    if (!Number.isInteger(n) || n < min || n > max) {
      problems.push(name + ' must be a whole number from ' + min + ' to ' + max + '.');
      return fallback;
    }
    return n;
  };
  const oneOf = <T extends string>(name: string, options: readonly T[], fallback: T): T => {
    const raw = (env[name] ?? '').trim();
    if (raw === '') return fallback;
    if (!(options as readonly string[]).includes(raw)) {
      problems.push(name + ' must be one of: ' + options.join(', ') + '.');
      return fallback;
    }
    return raw as T;
  };
  const secret = env.JWT_SECRET ?? '';
  if (secret.length < 32) problems.push('JWT_SECRET must be a random value of at least 32 characters (for example the output of: openssl rand -base64 48).');
  const magic = (env.MAGIC_LINK_URL ?? '').trim();
  if (magic && !/^https?:\/\//.test(magic)) problems.push('MAGIC_LINK_URL must start with https:// (or http:// while testing).');
  const config: Config = {
    jwtSecret: secret,
    accessTokenTtl: int('ACCESS_TOKEN_TTL', 900, 60, 86400),
    refreshTokenTtl: int('REFRESH_TOKEN_TTL', 2592000, 3600, 31536000),
    magicLinkTtl: int('MAGIC_LINK_TTL', 900, 60, 86400),
    magicLinkUrl: magic || null,
    allowedOrigins: (env.ALLOWED_ORIGINS ?? '').split(',').map((s) => s.trim()).filter(Boolean),
    rateLimitPerMinute: int('RATE_LIMIT_PER_MINUTE', 300, 0, 1000000),
    authRateLimitPerMinute: int('AUTH_RATE_LIMIT_PER_MINUTE', 10, 0, 1000000),
    trustProxy: oneOf('TRUST_PROXY', ['true', 'false'], 'false') === 'true',
    passwordIterations: int('PASSWORD_ITERATIONS', 600000, 1000, 10000000),
    signup: oneOf('SIGNUP', ['open', 'closed'], 'open'),
    sharedAccess: oneOf('SHARED_ACCESS', ['signed-in', 'public-read', 'anyone'], 'signed-in'),
    version: (env.APP_VERSION ?? '').trim() || VERSION,
    port: int('PORT', 8787, 1, 65535),
  };
  if (problems.length) throw new ConfigError(problems);
  return config;
}
