// Generated by Duxner Maker — starts the API on Node: reads the settings, applies migrations, listens.
import { serve } from '@hono/node-server';
import { getConnInfo } from '@hono/node-server/conninfo';
import { fileURLToPath } from 'node:url';
import { createApp } from './app.ts';
import { mailerFromEnv } from './auth/mailer.ts';
import { ConfigError, readConfig } from './config.ts';
import { runMigrations } from './db/migrate.ts';
import { readMigrationsDir } from './db/migrations-fs.ts';
import { createPgDb } from './db/pg.ts';

function stop(message: string): never {
  console.error(message);
  process.exit(1);
}

const config = (() => {
  try {
    return readConfig(process.env);
  } catch (e) {
    return stop(e instanceof ConfigError ? e.message : String(e));
  }
})();
const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) stop('DATABASE_URL is not set. Copy .env.example to .env and fill it in.');

const db = createPgDb(databaseUrl);
if (process.env.MIGRATE_ON_START !== 'false') {
  const dir = fileURLToPath(new URL('../db/migrations/', import.meta.url));
  await runMigrations(db, await readMigrationsDir(dir), { allowDestructive: process.env.ALLOW_DESTRUCTIVE_MIGRATIONS === 'true', log: console.log });
}

const app = createApp({ db, config, mailer: mailerFromEnv(process.env), clientIp: (c) => getConnInfo(c).remote.address ?? 'unknown' });
const server = serve({ fetch: app.fetch, port: config.port, hostname: '0.0.0.0' }, (info) => console.log('API listening on port ' + info.port));

for (const signal of ['SIGINT', 'SIGTERM'] as const) {
  process.on(signal, () => {
    server.close();
    void db.close().finally(() => process.exit(0));
  });
}
