// Generated by Duxner Maker — "npm run import -- data.sql": brings in the data Maker exported (Data › Advanced › Move data).
// Applies the migrations first (so every table is there and current), then runs the file — its rows are plain
// INSERT ... ON CONFLICT DO NOTHING inside BEGIN/COMMIT: rows that are already here are kept, never overwritten,
// and if anything fails nothing is written. In Docker:  docker compose exec api node scripts/import.ts /tmp/data.sql
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { runMigrations } from '../src/db/migrate.ts';
import { readMigrationsDir } from '../src/db/migrations-fs.ts';
import { createPgDb } from '../src/db/pg.ts';

const url = process.env.DATABASE_URL;
const file = process.argv.slice(2).find((a) => !a.startsWith('--'));
if (!url || !file) {
  console.error(!url ? 'DATABASE_URL is not set.' : 'Say which file to import:  node scripts/import.ts data.sql');
  process.exit(1);
}
const sql = await readFile(file, 'utf8');
if (/^\s*(?:DROP|TRUNCATE|ALTER\s+TABLE\s+\S+\s+DROP)/im.test(sql)) {
  console.error('That file removes tables or data. This script only brings data in; run such a file yourself with psql if you mean it.');
  process.exit(1);
}
const db = createPgDb(url, { max: 1 });
try {
  const dir = fileURLToPath(new URL('../db/migrations/', import.meta.url));
  const r = await runMigrations(db, await readMigrationsDir(dir), { log: console.log });
  console.log('Tables are at ' + r.latest + '. Importing ' + file + '...');
  await db.exec(sql);
  const counts = await db.query<{ name: string; n: number }>(
    "SELECT relname AS name, n_live_tup::int AS n FROM pg_stat_user_tables WHERE schemaname = 'public' AND relname NOT LIKE 'auth_%' AND relname <> '_migrations' ORDER BY 1",
  );
  for (const c of counts.rows) console.log('  ' + c.name + ': about ' + c.n + ' rows');
  console.log('Done.');
} catch (e) {
  console.error(e instanceof Error ? e.message : e);
  process.exitCode = 1;
} finally {
  await db.close();
}
