// Generated by Duxner Maker — "npm run migrate": applies db/migrations/*.sql to DATABASE_URL and stops.
// Add --allow-destructive (or ALLOW_DESTRUCTIVE_MIGRATIONS=true) to run a migration marked destructive but not confirmed.
import { fileURLToPath } from 'node:url';
import { runMigrations } from '../src/db/migrate.ts';
import { readMigrationsDir } from '../src/db/migrations-fs.ts';
import { createPgDb } from '../src/db/pg.ts';

const url = process.env.DATABASE_URL;
if (!url) {
  console.error('DATABASE_URL is not set.');
  process.exit(1);
}
const db = createPgDb(url, { max: 1 });
try {
  const dir = fileURLToPath(new URL('../db/migrations/', import.meta.url));
  const allowDestructive = process.argv.includes('--allow-destructive') || process.env.ALLOW_DESTRUCTIVE_MIGRATIONS === 'true';
  const r = await runMigrations(db, await readMigrationsDir(dir), { allowDestructive, log: console.log });
  console.log(r.applied.length ? 'Done. Now at ' + r.latest + '.' : 'Nothing to do. At ' + r.latest + '.');
} catch (e) {
  console.error(e instanceof Error ? e.message : e);
  process.exitCode = 1;
} finally {
  await db.close();
}
