// Generated by Duxner Maker from data/schema.json — regenerate rather than edit.
// The tables the SQL in db/migrations creates, described for Drizzle ORM (typed queries in src/custom.ts).
import { boolean, doublePrecision, foreignKey, index, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export const authUsersTable = pgTable('auth_users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash'),
  emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/** User's quick text notes */
export const notesTable = pgTable(
  "notes",
  {
    id: text('id').primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
    title: text("title"),
    content: text("content"),
    tags: jsonb("tags"),
  },
  () => [],
);

/** Tags for organizing notes */
export const tagsTable = pgTable(
  "tags",
  {
    id: text('id').primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
    name: text("name"),
  },
  () => [],
);

/** Recent search terms */
export const searchHistoryTable = pgTable(
  "searchHistory",
  {
    id: text('id').primaryKey(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
    query: text("query"),
  },
  () => [],
);
