// Generated by Duxner Maker from server/src/custom.ts › endpoints — do not edit: change that list and Maker writes this again.
// Each function calls one of your backend's own endpoints with the signed-in person's token (platform.backend).
import { platform } from '@duxner/platform';

/** GET /v1/fn/search-notes — Searches notes by title and content. */
export function searchNotes(input: { query: string }): Promise<{ notes: { id: string; title: string; content: string; tags: string[] }[] }> {
  return platform.backend.call<{ notes: { id: string; title: string; content: string; tags: string[] }[] }>("search-notes", input, { method: "GET" });
}

/** GET /v1/fn/get-note-tags — Gets all tags associated with a note. */
export function getNoteTags(input: { noteId: string }): Promise<{ tags: string[] }> {
  return platform.backend.call<{ tags: string[] }>("get-note-tags", input, { method: "GET" });
}

/** GET /v1/fn/get-all-tags — Gets all tags in the system. */
export function getAllTags(): Promise<{ tags: string[] }> {
  return platform.backend.call<{ tags: string[] }>("get-all-tags", undefined, { method: "GET" });
}

/** POST /v1/fn/add-tag-to-note — Adds a tag to a note. */
export function addTagToNote(input: { noteId: string; tagName: string }): Promise<{ success: true }> {
  return platform.backend.call<{ success: true }>("add-tag-to-note", input, { method: "POST" });
}

/** POST /v1/fn/remove-tag-from-note — Removes a tag from a note. */
export function removeTagFromNote(input: { noteId: string; tagName: string }): Promise<{ success: true }> {
  return platform.backend.call<{ success: true }>("remove-tag-from-note", input, { method: "POST" });
}

/** GET /v1/fn/get-note-count — Gets the total number of notes. */
export function getNoteCount(): Promise<{ count: number }> {
  return platform.backend.call<{ count: number }>("get-note-count", undefined, { method: "GET" });
}
